name: CI-CD SIAKAD

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout kode
      - uses: actions/checkout@v3

      # Setup PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Install dependencies
      - run: composer install --no-progress --prefer-dist --optimize-autoloader

      # Jalankan test
      - run: php artisan test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy ke server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/proyekmu
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize
